-- DDL(DATA DEFINITION LANGUAGE)

-- CREATING DATABASE
CREATE DATABASE UNIVERSITY;

-- DELETING DATABASE
DROP database UNIVERSITY;

-- USING DATABASE
USE UNIVERSITY;

-- CREATING TABLE
CREATE TABLE COURSE
(
COURSEID INT auto_increment,
COURSE_NAME VARCHAR(30),
FEES INT,
DURATION INT,
PRIMARY KEY (COURSEID)
);

CREATE TABLE STUDENT
(
STUDENT_ID INT auto_increment,
STUDENT_NAME VARCHAR(20),
AGE INT,
MOBILE INT,
COURSE_ID INT,
PRIMARY KEY(STUDENT_ID),
FOREIGN KEY(COURSE_ID) REFERENCES COURSE(COURSEID)
);

DROP TABLE STUDENT;
DROP TABLE COURSE;

